### ISSUE TITLE
core dump CAFE

### ISSUE THREAD

**Issue by htafer** [hahnlab/CAFE#33]
Hi!

I get a segfault during Viterbi in CAFE 4.1 and 4.0.1 (did not try other versions). I tried different number of threads and number of families, but i receive a segfault.

My CF input:

load -i temp  -p 0.01  -l COGCAFE.csv.small.log
tree ((((((friEnd5311:11,friEnd534:11):38,friSim5184:50):114,horWer:164):292,((((aspFum:109,aspRub:109):67,claCla:176):130,(claImm:95,exoDer:95):211):130,acaStr:437):20):132,sacCer:590):41,schPom:631)
lambda -s -t  ((((((1,1)1,1)1,1)1,((((1,1)1,1)1,(1,1)1)1,1)1)1,1)1,1)
report COGCAFE.csv.small.results

My family input

FAMILY  acaStr  aspFum  aspRub  claCla  claImm  exoDer  friEnd5311      friEnd534       friSim5184      horWer  sacCer  schPom
0PFTW   4       8       10      6       11      7       11      15      11      10      3       9
0PFSV   4       4       2       7       9       11      8       9       9       13      18      8
0PFMP   2       4       4       10      13      12      8       8       6       7       1       2
0PFRH   2       3       6       4       3       4       6       9       10      10      2       3

If i use valgrind to profile the memory the process does not crash! So probably a memory corruption problem

Thank you

**Comment by htafer** [comment]
solved by adding two columns to the family file. Header ROW should contain FAMILYDESC and FAMILY columns. maybe some warnings during the file parsing might be indicated

FAMILYDESC      FAMILY  acaStr  aspFum  aspRub  claCla  claImm  exoDer  friEnd5311      friEnd534       friSim5184      horWer  sacCer  schPom
STUFF   0PFTW   4       8       10      6       11      7       11      15      11      10      3       9
STUFF   0PFSV   4       4       2       7       9       11      8       9       9       13      18      8
STUFF   0PFMP   2       4       4       10      13      12      8       8       6       7       1       2
STUFF   0PFRH   2       3       6       4       3       4       6       9       10      10      2       3

**Comment by binhologia** [comment]
Hi there,

There's a new version of CAFE coming up that will simplify the user's life
quite a bit. Stay tuned.

Cheers

On Feb 22, 2018 9:15 AM, "Hakim Tafer" <notifications@github.com> wrote:

solved by adding two columns to the family file. Header ROW should contain
FAMILYDESC and FAMILY columns. maybe some warnings during the file parsing
might be indicated

FAMILYDESC FAMILY acaStr aspFum aspRub claCla claImm exoDer friEnd5311
friEnd534 friSim5184 horWer sacCer schPom
STUFF 0PFTW 4 8 10 6 11 7 11 15 11 10 3 9
STUFF 0PFSV 4 4 2 7 9 11 8 9 9 13 18 8
STUFF 0PFMP 2 4 4 10 13 12 8 8 6 7 1 2
STUFF 0PFRH 2 3 6 4 3 4 6 9 10 10 2 3

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/hahnlab/CAFE/issues/33#issuecomment-367693440>, or mute
the thread
