### ISSUE TITLE
The cafe software, the error happen as below 'Failed to load tree from provided string (branch length missing)' 

### ISSUE THREAD

**Issue by xiaojikuaipao** [hahnlab/CAFE#51]
Hi,my firend:
 when I process the cafe software, the error happen as below 'Failed to load tree from provided string (branch length missing)'. Can you tell me why?
 Thank you for your help,
 Look forward to your early reply.

# #!cafe             
# load -i ../data/filtered_cafe_input.txt -t 4 -l ../data/reports/log_run1.txt
-----------------------------------------------------------
Family information: ../data/filtered_cafe_input.txt
Log: ../data/reports/log_run1.txt
The number of families is 14266
Root Family size : 1 ~ 124
Family size : 0 ~ 149
P-value: 0.01
Num of Threads: 4
Num of Random: 1000
# tree (((((('isc':0.0846235,'aae':0.0846235):0.0204677,'hsa':0.1050912):0.0151122,'dme':0.1202034):0.0926185,('cel':0.1540424,'mma':0.1540424):0.0587794):0.0571893,('tur':0.2572301,('dpu':0.1439780,('dsi':0.0753659,'dma':0.0753659):0.0686121):0.1132520):0.0127810):0.00E+000,('cin':0.00E+000,'sma':0.00E+000):0.2700111);
Failed to load tree from provided string (branch length missing)

**Comment by benfulton** [comment]
Hi,

A couple of the branch lengths you have are zero, such as the "sma" leaf. Zero lengths aren't allowed. I'm also guessing that your tree isn't ultrametric. For CAFE, a tree is needed with branch lengths in absolute time, which means you'll have to do some divergence time estimation on your phylogeny. We recommend the program r8s for this purpose since it is very fast. There are other discussions on the forum and in the tutorial regarding how to use r8s to get a tree suitable for CAFE.

**Comment by switchon08** [comment]
Try changing all species names to lowercase letters
