### ISSUE TITLE
cafetutorial_draw_tree.py errors

### ISSUE THREAD

**Issue by haojingshao** [hahnlab/CAFE#67]
Hi hahnlab,
Thanks for answering my previously problems.
Now, I try to use cafetutorial_draw_tree.py to draw figures. Question1: is there a way to draw both duplication and contraction? 

Question2: I get the following errors:

CMD: python ~/bin/CAFE/python_scripts/cafetutorial_draw_tree.py -i reports/summary_run1_node.txt -t '((((((Apl:595.291098,Spu:595.291098):227.831852,((((Xtr:310.000000,Hsa:310.000000):88.528977,Dre:398.528977):328.153022,Cin:726.681999):43.561163,Bfl:770.243163):52.879787):54.262035,((Cel:746.070139,Dme:746.070139):72.072332,(Lan:725.114368,Cte:725.114368):93.028103):59.242514):50.908402,Nve:928.293386):71.973081,Mle:1000.266468):41.094350,(((Xbe:427.510190,Aqu:427.510190):307.135463,Twi:734.645653):306.586788,(Oca:883.727749,Sci:883.727749):157.504692):0.128376)' -d '((((((Apl<0>,Spu<2>)<1>,((((Xtr<4>,Hsa<6>)<5>,Dre<8>)<7>,Cin<10>)<9>,Bfl<12>)<11>)<3>,((Cel<14>,Dme<16>)<15>,(Lan<18>,Cte<20>)<19>)<17>)<13>,Nve<22>)<21>,Mle<24>)<23>,(((Xbe<26>,Aqu<28>)<27>,Twi<30>)<29>,(Oca<32>,Sci<34>)<33>)<31>)<25>' -o reports/summary_run1_tree_rapid.png -y Rapid 
[summary_run1_node.txt](https://github.com/hahnlab/CAFE/files/3577684/summary_run1_node.txt)

Traceback (most recent call last):
  File "/home/uqhshao/bin/CAFE/python_scripts/cafetutorial_draw_tree.py", line 84, in <module>
    draw_tree(args.input_file, args.tree_type, args.tree, args.id_tree, args.output_file)
  File "/home/uqhshao/bin/CAFE/python_scripts/cafetutorial_draw_tree.py", line 58, in draw_tree
    Phylo.draw(tree, axes=fig.gca(), do_show=False, label_func=label, label_colors = lambda n: colors[tree_type])
  File "/opt/biotools/biopython/lib/python2.7/site-packages/Bio/Phylo/_utils.py", line 497, in draw
    % (key, value))
ValueError: Keyword argument "label_colors=<function <lambda> at 0x7f381aad5c08>" is not in the format pyplot_option_name=(tuple), pyplot_option_name=(tuple, dict), or pyplot_option_name=(dict) 

Thanks,
Haojing

**Comment by benfulton** [comment]
The script takes a --tree-type argument with the values "Expansions", "Contractions", or "Rapid" which allows you to draw those particular trees.

The error you're seeing most likely indicates an out-of-date BioPython package - if you upgrade to the latest version that error should go away.

For questions about CAFE you should use the Google group hahnlab-cafe (https://groups.google.com/forum/#!forum/hahnlabcafe ) rather than opening Github issues. Thanks!

**Comment by U201412486** [comment]
Hi,
  I am sorry that I can not use the  google group hahnlab-cafe ,because I do not have a google account.
  When I use cafetutorial_draw_tree.py ,it reports error below.
  `Traceback (most recent call last):
  File "/software/CAFE/cafetutorial_draw_tree.py", line 83, in <module>
    draw_tree(args.input_file, args.tree_type, args.tree, args.id_tree, args.output_file)
  File "/software/CAFE/cafetutorial_draw_tree.py", line 57, in draw_tree
    fig = plt.figure(frameon=False)
  File "/lib/python2.7/site-packages/matplotlib/pyplot.py", line 533, in figure
    **kwargs)
  File "//lib/python2.7/site-packages/matplotlib/backend_bases.py", line 161, in new_figure_manager
    return cls.new_figure_manager_given_figure(num, fig)
  File "/lib/python2.7/site-packages/matplotlib/backends/_backend_tk.py", line 1062, in new_figure_manager_given_figure
    canvas = cls.FigureCanvas(figure, master=window)
  File "/lib/python2.7/site-packages/matplotlib/backends/_backend_tk.py", line 173, in __init__
    width=w, height=h, borderwidth=0, highlightthickness=0)
  File "/lib/python2.7/lib-tk/Tkinter.py", line 2176, in __init__
    Widget.__init__(self, master, 'canvas', cnf, kw)
  File "/lib/python2.7/lib-tk/Tkinter.py", line 2036, in __init__
    (widgetName, self._w) + extra + self._options(cnf))
_tkinter.TclError: unknown color name "white"`
  Can you give me some advice？
  Thanks,
  sun

**Comment by benfulton** [comment]
Only that it seems to be an issue with your Tk install. You might try reinstalling that, or, if you are using a machine that requires X forwarding to display images, you might try it on a different machine.

**Comment by U201412486** [comment]
Thanks,I will try.
sun
