### ISSUE TITLE
Files for cafeerror.py missing

### ISSUE THREAD

**Issue by DerZoger** [hahnlab/CAFE#95]
Hi,

I just tried running the cafeerror.py script for part 3.4 of the Cafe Tutorial PDF, however the tutorial files I downloaded seem to be missing one of the pre-computed run6_cafeerror_files. Therefore the cafeerror.py script yields the following error:

IOError: [Errno 2] No such file or directory: '/<path_to_tutorial_files>/cafe_tutorial/reports/run6_caferror_files/cafe_0.110888671875_all_log.txt'

Except for that error the script runs without any problems. I've checked and indeed said file is not present in the https://iu.box.com/v/cafetutorial-files share I downloaded and might have slipped through the cracks when uploading the tutorial files. I would be very grateful if you could upload the missing file to allow successful execution of said script.

Christopher

**Comment by gwct** [comment]
Hi Christopher,
I think you are right that I don't see that particular file in the folder.
I see the error model file (cafe_errormodel_0.110888671875.txt), but not
the log file that you note. Someone who still has access to the Box folder
will have to check that out.

I am a little confused though, and it's been a while since I've worked on
this tutorial so maybe I'm misremembering, but when you run the caferror.py
script it should generate everything for you. It shouldn't be looking for
those files to be pre-computed. Can you send me the command you are running
so I can get a better handle of what's going on?

Again sorry if I'm misunderstanding, but I just wanted to chime in.

-Gregg

**Comment by DerZoger** [comment]
Honestly I didn't deviate much from how the process is described in the manual. I've used the exact same command as is shown on page 17 of the tutorial PDF, specifically this one:
`python  caferror.py -i cafe_shell_scripts/cafetutorial_run6.sh -d reports/run6_caferror_files  -v 0 -f 1`
Obviosly I've adapted the paths to my particular system, but left the important bits untouched. During runtime it didn't seem like the script was creating the log files, but rather parsing them, but I might as well be wrong just like you 😄 
I'd be very happy if somebody with access to the Box folder could add that file!

**Comment by benfulton** [comment]
Indiana University no longer supports Box and so that directory and link are now defunct. But you should be able to find that file at https://github.com/hahnlab/cafe_tutorial/tree/main/reports/run6_caferror_files

**Comment by gwct** [comment]
Thanks, Ben. Hopefully getting the files from there resolves it and I'm
just mis-remembering how the caferror script is run in the tutorial. But
let us know if you have any more problems even with those files.
-Gregg

**Comment by DerZoger** [comment]
Hi Ben,

I must admit that I can't try the new GitHub files right now since I'm currently away from my workstation, but I highly doubt they will work, because the issue I pointed out with the Box files still persists in the GitHub files as well. There are 22 error models in the folder you linked, but only 21 corresponding log files. Said log files are however required to run the caferror.py script successfully. Therefore with the files missing it probably won't be able to finish, just as it couldn't with the Box folder files. Long story short: The file cafe_0.110888671875_all_log.txt is required, but not present in either the Box folder, nor the GitHub repository and has to be added. I would also offer to do this myself, but I unfortunately don't know how to go about creating it...

**Comment by DerZoger** [comment]
> the issue I pointed out with the Box files still persists in the GitHub files as well

I'm now at my desk and retried using the GitHub-hosted tutorial files. The issue unfortunately still persist. As mentioned running the cafeerror.py  like so `python caferror.py -i cafe_shell_scripts/cafetutorial_run6.sh -d reports/run6_caferror_files -v 0 -f 1` the script fails to retrieve the scores for the 0.110888671875 error model and throws an IOError:

CAFE run number 21
0.110888671875 Error Model Run for all
Rewriting CAFE shell script...  
Running CAFE [silently] with error models listed above...  
CAFE run complete! Retrieving Score..........  
Traceback (most recent call last):  
  File "<path_to_tutorial_files>/caferror.py", line 578, in <module>  
    currentScore, currentLam, initCheck = getScore(currentError, spec_to_min, tmpDir, 1, caferrorLog);  
  File "<path_to_tutorial_files>/caferror.py", line 270, in getScore  
    sFile = open(scoreFile, "r");  
IOError: [Errno 2] No such file or directory: '<path_to_tutorial_files>/reports/run6_caferror_files  /cafe_0.110888671875_all_log.txt'

**Comment by gwct** [comment]
Hi again Christopher,
I want to make sure there isn't an underlying issue here. I wrote the
original caferror script and didn't put in any resume option or extensive
file checking, which means if everything else works it should create all
the necessary files, including the missing log file you've pointed to. Just
to make sure, I downloaded the tutorial from github and ran the command you
sent. At first, caferror sped through everything until I got the same error
that you're seeing with the missing log file.

But the problem was that CAFE wasn't being run at all because the path to
the CAFE executable in the input script (the first line in
cafe_shell_scripts/cafetutorial_run6.sh) was set as the path on a local
user's computer. If I looked at the output on the screen, even for the runs
where it found the log file (because it was already in the output folder),
I noticed that CAFE wasn't actually running because it couldn't find the
CAFE executable: sh: ./caferror.sh:
/Users/binho/Documents/IU/hahn_lab_stuff/CAFE/release/cafe: bad
interpreter: No such file or directory. However, once I changed the CAFE
path to the path on my machine, caferror.py ran and finished successfully
because it created all the files, including the missing logfile, along the
way.

Can you check if you've updated the path in the input script? Even if
you've already changed this path, my guess would still be that something
else is wrong and CAFE isn't running correctly in the background. Otherwise
that file would be created as caferror runs.

-Gregg

**Comment by DerZoger** [comment]
Hi Gregg,

you are a genius! That actually did the trick. I actually had it changed, but only to the directory containing the binary and not the binary itself (my bad). Thanks for taking the time, now everything works as expected!

Christopher
